# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/aaa/UCAS_CAlab_19/exp20/mycpu_env/cache_verify/run_vivado/project/loongson.srcs/sources_1/ip/data_bank_ram/data_bank_ram.xci
# IP: The module: 'data_bank_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/aaa/UCAS_CAlab_19/exp20/mycpu_env/cache_verify/run_vivado/project/loongson.srcs/sources_1/ip/data_bank_ram/data_bank_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_bank_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/aaa/UCAS_CAlab_19/exp20/mycpu_env/cache_verify/run_vivado/project/loongson.srcs/sources_1/ip/data_bank_ram/data_bank_ram.xci
# IP: The module: 'data_bank_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/aaa/UCAS_CAlab_19/exp20/mycpu_env/cache_verify/run_vivado/project/loongson.srcs/sources_1/ip/data_bank_ram/data_bank_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_bank_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
