webtalk_init -webtalk_dir d:/Desktop/gitclone/UCAS_CAlab_19/exp21/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.sim/sim_1/behav/xsim/xsim.dir/tb_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Dec  4 22:12:11 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1a509337-b8ce-46b0-a572-6d022112a7ca" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8805a049773944b490f8095f97dc5924" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "49" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5700U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1797 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "49" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "2116 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "284 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "5594" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "480" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "4.44_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "347944_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4084908371 -regid "" -xml d:/Desktop/gitclone/UCAS_CAlab_19/exp21/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.sim/sim_1/behav/xsim/xsim.dir/tb_top_behav/webtalk/usage_statistics_ext_xsim.xml -html d:/Desktop/gitclone/UCAS_CAlab_19/exp21/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.sim/sim_1/behav/xsim/xsim.dir/tb_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm d:/Desktop/gitclone/UCAS_CAlab_19/exp21/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.sim/sim_1/behav/xsim/xsim.dir/tb_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
