# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/aaa/UCAS_CAlab_19/exp20/mycpu_env/cache_verify/run_vivado/constraints/cache_top.xdc

# IP: D:/aaa/UCAS_CAlab_19/exp20/mycpu_env/cache_verify/rtl/xilinx_ip/clk_pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_pll || ORIG_REF_NAME==clk_pll} -quiet] -quiet
